#!/bin/bash

while read oldrev newrev refname
do
    branch=$$(git rev-parse --symbolic --abbrev-ref $$refname)
    if [ "master" == "$$branch" ]; then
	git --work-tree=${target_dir}/${proj}/${django_proj}/ --git-dir=${target_dir}/${proj}/repo.git checkout -f master
        # Do something
    elif [ "beta" == "$$branch" ]; then
	git --work-tree=${target_dir}/beta_${proj}/${django_proj}/ --git-dir=${target_dir}/${proj}/repo.git checkout -f beta
    fi
done

